services:
  db:
    image: postgres:15
    container_name: workout_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: workout_web
    command: sh ./start.sh
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./src:/app
    working_dir: /app
    restart: unless-stopped

volumes:
  postgres_data:
