"""initial schema

Revision ID: 8a2c4d84328d
Revises: 
Create Date: 2025-12-24 01:15:14.299601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a2c4d84328d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('duration_mins',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('session_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('muscle_group',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('sessions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_column('split_type')

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('num_sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_reps', sa.Integer(), nullable=True))
        batch_op.alter_column('muscle',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('workouts_session_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('workouts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['session_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workouts_user_id_fkey'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('workouts_session_id_fkey'), 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
        batch_op.alter_column('muscle',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('num_reps')
        batch_op.drop_column('num_sets')
        batch_op.drop_column('exercise_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sessions_user_id_fkey'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('muscle_group',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('session_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('duration_mins',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('session_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
